### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by shaunroot** [giero/LGoH-deck-suggester#3] opened 2017-12-19 20:21 UTC
I was trying to set up a commander deck that works against fire. This is what the site suggested:

**Sentinel Of Stars (6*)**  Light Warrior Technological  ::  2247 / 187 / 3744 Light Commander 4x
**Brutus Mark 3 (6*)**  Light Attacker Technological  ::  2914 / 389 / 1947 Light Commander 4x
**Paladin Ivon (4*)** Light Attacker Dren  ::  1141 / 153 / 767 Slayer 2x
**Sentinel Of Stars (6*)** Light Warrior Technological  ::  2247 / 187 / 3744 Light Commander 4x
**Stellaris (4*)** Light Mage God  ::  655 / 218 / 281

The three Light Technological heroes make perfect sense to me. I don't understand why the site suggested two 4* light heroes that do not receive a bonus from the leader (not light technological) and are not for commander events. I would think the site would at least suggest one of my 6* water heroes or my 3x commander hero. 

Is there a bug or is the app teaching me something that I don't know about the game?

Thanks!

**Comment by giero** [comment] 2017-12-19 20:59
Hi,

Could you paste your exported team here?

**Comment by shaunroot** [comment] 2017-12-19 21:02
NobwRAlgJmBcBMAaMBjA9gJwKYEkazADMBWAIwHZiBOeARjGQDsBDAWyzjAEFsBnBsBmYYIAFwCecACzJmAd2YBrLIwiMA5nAAMswoTVjJBAGIRsAiQAcOBAOrCRmAb2soIWfgQAiWVhHVoMLKioswoinDkABzEyNjoAG5YGEYAbOTIABZYzAA2oplwtADMWhlgWEmMogDKihC5uZ7g9hhQKnCiGACuWAC+yO2EKu0YdQ25nAAqmZiM-Mjo3dXJ442cXhAuWLkABABKWOodyLk5o1ykDYZw4O28KCKWohBojJzwqVoApAcAogBhXaETC7PJ7UzYXYACWSaA8AlYgQg+mSzUEWESySM8AAdKkBmAWOxOJCsLsAEJnXi8NTqXY4ABqFmEx1EpLMHEJlTQuSSxgwaFYnAEPL5uGqaE4UGItC0WGKpFSYAG4Gg0kWmFw+DA5GK8HgzEItFIAmJNjAAAU8swoGoGQk3gIhCIJBqwPIlCo6dpdPpVG6CAAZfyZdnIKwWrghMLKDDOVzuTxgLzYd7BULhIq0KS0OKYtBJFJFYjFLI5fKFWDkdLISoqWr1Rromq5ZjiZJweCEoYjVZNyYELhtx43TXLUT9iYbLbWPYAcV8NQaKhQHFO52Sl2ugbuHlHz1e7wItC+vy8bGYx2BoPBMLeWqgMLhCOQSLtqIw6OYMazsFo+KEuanDQg+2BPgAsqGogMsyEaslg7IEKBjCPiqdaOuKApCiKGG8kkOCStKKBROQpDylo6FqvgsSoFqeCcMUUgoMQpbEMwZpsBaPj6Mw1S7AAUmgfHOsINywDIHoKMoqgaL6Hp6AYgZgPYk7xhG4jWJwFI2owa5BGA2xuAiyHdKwIkZrGcDELm+ZYsW-5RDoYDZHkBRwFQWhIBUVSNhMLZth28YID2WDDIwoxrIO3AYEi6l0ROU7rN4s47JSuRqAZZy2luVwZbuYD3AeLxOieZ4wpaN4YGCjSUrp+nPoKr5gO+KLuF+twuRW7n-oBTBcdp9VYE+PBxbBLIYGyg1tnpw3oT5+FYNhwoEKKmEEURBDMKkxQmlEqSEFRkD4KkmrYAxBBRHQXxSIQVCcSSdhppSaDqLwuxTIKmhxGJgaSZ6Mk+rAzlGv64lgH8wjuRpWkEPO3TCHaFmGYmJlgPOEB8eGHq-hE-6pFQdmFtiXa0FE5ZuVWcpRITPkNlFzSheFkUDpwo1OOOKxjKzKXbHsjIeLwOwCNlFx5eJe4PE8JXHmAp4-BVVU1QumP8bCTULC1yKfuirmVkUfVEgNcOqzB7PVUyE1TSbWPzWK-KCitYBrYthGiFKBCpHQtDEMaURHeq1ZndqnDkOQUA+2ElH9Y9YA1JOjRiZrLrif90nenJwN+kpRhgCG6hhhYmkWhBV7rijmJJpw86BAIP6ZnjqSsUTRY4mTFP6wgUR5nT1QM51FJoBO4gwolwXdoMYV9tz04EFSmUCEsXNRTOfO7JcvCYKaG45Rg275UYkvFUenDy+el7XiC1V3qmV5vI18Ka61OudfXVm9QSMfcUIASMLsUEFxgpbeCk1EIbB-k6bk60lqO1wgtcUbsPa6lSFIcitBtoB3wOTOi50dSkUIFoYowx6Bf04ACYQ5k9gzGWKMUgVkfquiMGnL0slNBZwUmDZS+dC4wwtPDRGqsEyVzRhjW2lk-ynlOhieybdyh6x6tTco9Y+4DkZpPZmSVorm0XkPZePMUypX5oLYWO8xY7kPoVfc0sT5lQVtCSqV9la7FEWrF8T9tbtV1t1KmhtgI234ubcaIDrbo1NnbaBy04H2wlO7TgO0m5UGKFgcgmCPLBwumAVIzBbQoCoFQYgD0LT2CSLwLoQpdgAlyGgSwydfpMNkOnVh8lQY504KpTsvDq4IzaII5ARkq7+Oxm-CRTcW4kwQLQOR3iihaFIhhemqjbhM2nivIcsUOYJT0bPAxa8BY0hMWAUWuVzGdSKtY0qctyr2KVneFxMF1aP0RB4tEnV5E+M-kbWOdz17rItnBMAoRQFIVCbbKBi1ImrTwggzaYAtAoDoKQQgdBUn-mcugXBnB9rMCkLtUohS2YYBkrMXIT5PqvVEow90AMM5sJBopAMucyRF1hujbpSN0wV2MsmO5ddcZFC9mMhy10O4KNmd5ZRflmxLPUSs-R2jOZqVWTsucuw9lC0mKY45B9TlWIgIeC5Z9FaONuabB+zVn6eNedMj+QFjYgoCb8oJAKELAp5WCrCsDIXwI2rEgg8AUDpB2rtFFtBvLopDieFAtAqAxHgFIfFQ58jJD4v-PiowMpyQYanBpLCgZ0s4YyzkzKikOFePFfpaNb6-15Q3OAqRJmCqMLKEVVMvJKN8v3WAIBlkRU0QSuKOix5Ks2GvZclhZgcqOXvcWBUzl6plqfcqF5zKX1vLVVojhqoPPNc8jqXaca1ptaQuwpbQQALDE6wFISN1lvCeCz1zsoU+qQcNUgtATTMGKCGssOCI1gBjeQLQzBiDkA4seuOgLMjMCqOvEIIwxGCDqVSxpebs4Ms4Nw7GkYNhT17eW1G3KwniLxvAKgUj4jEwcjGltRQDSSQlZ27tMq8NKtsDkGSg6tnJWVWlS0aAthOk1dOk5+6536tloa65xrarfO3e4j8lr91vINh8vx9qzaOuAc6oF1cwnuodjhL10TEGcCoIQcgt0czwBDbRcNGS6FYCoLQKA+SE1gAAKoYAKMkXYVa3gZu+ohylsAf3Uqaewlp6GT1qWLW009+HhHJj8xy4ZeNigoMbXAXaNHYBfCkQxxZXae0s22XxgTHKl6Kv0SOlVt81Ai03MJ7VondXidPlIOxDi117HaVutxTyFMvKU9agCUhbWx16z8saOAZtWzAdFzs+mYGGcfd6mJSCUB0KiIQKQIGQ1SLszqGsURgPEGSW5gA8m0EQKBfMQMYAFil4lQsoczvm1p3hhARE6SejAm6hFcvAXfFLfKQv1syyF5yyncteXmSo-y0rLEaJntxsrm8Ku6Kq9smraU6uTsa-vCWlipbzpsXLDrvwpPdd819s18m2pDfAND0b43uK08CTNnAc3gUXkJXej1K2XbQt9WAYoxAoDwAVMUFAIbyiHcYrKIh5BCDKnAz4LAlgkQ0lTaUnzqZujqizYGF7ua3tofBpDLzhQftgFhHkDpnKBm27MsjVLRQnIQ5zLTaHpHaYFYR0V5jJXuOHGOBjod1XDG7DR4Jw5BOZ0WLEwuk8FP-hAmk3sS3BQ6cDYZ3u8AFHW4GzG+BrPmR0qCzpAyWbwT5sQyhoUJbELUD+uxbtGXT71silVMdd36SdTS9maQViYHPkWgEtB7ovBEB3eB9HwUk4UDu3iinQMtEwuoY4R9sATKbfRgbg7ityYASYB6M8Gt79JlOYh-AYo3uRvRuwf7qV+6T+sHMnhrLxW+2JrCJShVP+PGVCaAAAHvVkJoTrOq1snnLE5JTl1tfLVFMJiJkKhFUuoBACgHkDnm+Lul4pTAbFEKztMCgWga9JgdgYEv8lenXsgSgKgbyOQVgZME3g+nKJtnKGHELs+pwFgI-lZv7D3oHPAGivRDqMwFQFAKQJ5E5G5gKFgOIAAFaj6r5pA5qAxm5b5RYqQ-gO7Ya-b-Z9IEbVy1zEZdgdbOSF7jIiGSTQ4WHOTP5NCdStjtidgSTf4o7RR46cZY7cY457Dypx67yQGJ7QFk6lAKzLplxggRRGrU6TY1xPhya54vz7pu4hY5bFDEELbVSJH-zQSXoupwDAA6ExbICJFgAAC6rBK2WgXsoapAca3BXeq0Qh+AdA-enAxAhC0u7BbmPgjoQgmQM+Mw5IEEaAbwpAuiBkqh1k6hNKzS9K4MvO32AKxcbMuMh+xh3gvg-gphB6l+u0tEVhDkkyUyBBsAUQ+0cOkqThgeSOsq2OgQxwPhgB-huwY6E6DWwRCeOqJObWJ4cBNOK65IGeo8H+OBWsg2+eBxEiuIRB4G0ILuf856ME1BRRpkH+-OBmTsCoVA2Su08aneJmBAWgEcUgt0UQMubRXYYaYhnApATEKAXkrm4GhwEAM+yWoQuQcYT2f08x4W722hu+axLKOkM0+kAOTuQYRwIwF+f45AOYN+xQ2CzOZMfuHahW4ALhQUXYyAg8w8o8XMepYAb+H+owXYHhSqAAit0rkAAOTvSWgL6YgLoAGeFsykCbzijfFmLNZHznISZLoXzkhppxGIEQiciQkWqM6wl4wARSLM6+J2pkjR5oByA+ZaY0HApMo1FOwiHdynisTNEklyxaClh36JIoq36dEEDmYkD4kq5uZBjLCYzrxTF+AsBulBbZpSSm60rm7KQrGxZwxsq9KO4iJEZxn8q0wnFtyqkjZaBUD0aakB5MYPEsZyq-KvEem8wqpqoHJTohF-HHwGpXIIFOKyb9a4HQn4GdwJnZHqZTaghZkYnqbYnLZOwlkwqyh6CeS+zVmSTy4niEBRqzJRAGRqYUg5DdBuhG71J9kaEDlaEW4N4jncCbEJaA6Ymu6g6JLHEFhF7-hxo5Zez5arkv7amBRuETwbnB5eFCDgGbK+FeFR6fTMBiAbJHm-Etb-EwGfAKz7CAg3IyZjkprJE3l57ohzldjJlfJiV-xUiV4aCFE6ajkCIiR5lRLQKlnkTlnJIUDVkHb0l1moKEJaB3RuY1DiC5DjruC7AXaED-wTF-zziChJB8lqGIULERZLFDlfboU3obJH6cA1CWBmBiDykkZxrlAyWOTnGdzFAWYrkLJrmmlCjmluEl50WAEzBzCayVZvFR5sYsK+lapE5J7hFaCREhkxFJEXk3y05hURX3LXlQlSWvyg4-rQ5ZFq5NXhWuj5GAKqXWwlHDnIDNWuhVFaVlTDQ2RIrfki7Vly4mVECSIoBQDAZuYABy0EpSeQcY0e3QlgnlyG-ZixBaGwAVNuQVWFTuyWUVda7c0ilGTa3kzO5lNxjGVpW5A67pw6Uenxse3FImAZpOZ5NVIJIlPW8W0ZeBnVh6D54Gt1Q1F6r5alOhf2t6M1q2xmMKy55A8AsoFJ1ZtMwFRAOKlA0Q-s4GxguQ4gVeQYaAogU+p1uWApm+kWqFVugV8WUpaMKEaEZhCAMVnucyXUFxSVFJX1Wpcc1FwU2VvYm52y88EUO5ANa8eVGA8wZVTWFVYRFyER58UNYZVOEZuwZe94qE4EcNt5CN783V1qvVY+nAltgtNtqJI182JRZeAg7tc01Rneze4c6QFlVJi1SCKKpQtZuot+UgEuTZ4GUwhYwgM+3muwtgdI1ItSwWzCSFF12+mG6F++sYWxiWOGfgAQBk6RYcPccVco711qsotEjh6IBp1QI8SJxpIUQebxzx5chVu5QBHxeqXxEBPFYNAJlykN0RYJSJEJEl7VqR4A6RSNLtOFKJBR6NIS89mlQdD6EdnAS52KzAWA3RUddJGKBA1AUA6QKAiozZtoI8AA0lgJyH-GgE5RSCIByrMRJBzZoVzcpL1uheKXxJKUYeXRvY9bAMQDtGLQlT1Iku2qlZRWAO3RIEaTFj3TlUPaHicMxUVWvDHvjj8aDcTqeUGZ1tDeCeJW1TGTCUmapnarvX-BzuiRjawx+c3ofQQFQFgATLtOQPdDSSFkBatUlfAIQFEI5uXGprtYAuZFCKYHKfBXMd5YKYOYWuYDbmA7NAZCFQQCfn9sdUMnhT7BDqULRMzsQCRb3LceiK0O0MeF0L0D9dsifmPG7v9fottW8OXCDf6RQ4GR8ECUJentTsY2fq1RrCkYpgXoRdYfCY+VE6YxXjSFXhwyEqk+fjjXdEksuSxLw0QDQMuexBxKI2LjHeQGFFIVgFIKPmplrWzVIhvoA35bnCA3vphfzdyvsekQJZYYkw5CqVDiNp5A4RRXcVRa4Qre49xsnWAeHlxqxWvMYDkPFIE-rXxWTiITPauubT4JXYELbR1WkaDrRWpkc3sZBAUYyFzrXjzrsVXdww+sPrQJiATNvGtqWVAJtlQKQFgFI1HcZVfaLjZFklIaruvXHA2GoGlI5R8YCjneJK069shUA7nEXTdXzZA9hWAHQQwegRQRqtOSLVILFcM0YGTIg1WFLSlfDmg2aWmllfM9FPg8syxavCqiVRxuPeQ5VYbdVcbdEabQ1bVJhh9KQYwRgcwac8vWS47ZLY+ZK4S2QbK9gZ7dvd7XnNBAIGqzKyS9NfvStqQPHWHETdHD8zCn89IYC8C5UytWC2LlIJC0qFZXC4wAi05fHMICi4GGi+db5ZdcGHqzi1jcFdsQS9K8S8wTA3RpSzIu7rS1lslTLWlcy5-u4b3Xg7KZy0Qzy+xgQ1s1ATs0K-s6GbEWbU4qqzG0wdgYvQw9+F1ZkSqwUQa7G5q1vVkzq9i9G-Qeq0a4HWts3ma1ABa+fcSTa-8-a4dJU2TatUBjI7QCRNZuBtBYnDPnbl5s4mymzXnT5UKcsddaKSXGXL0yYdXaDjTIm69bRmMxcV8C3VMwFLM5aTm6xkW-m0Pe8arVlPHgKwbVQ-ATQysfK-ExLfeXJWzoSs+X8tzldXzjjcU1ANVaQKuzAKIx1jHcwGTCu-AO6+BpNWIA5U5QLBoDkLNPuwAxix0xyDo6e5wKXC8Xi07jk2Y4egTEM0myLffhcb7um5RWy5wNaKoB3oQz+1HqJ5gbrcebxZQ4uhWzQ+x+B7GavdB2Qqfmk1qz28Cux684LlOyLmRnGttk0Vhz3OTR1jWKgrY25lwOOoKHaJODPiGMMJSD-ccCvkhuzRo5zXRzkcXT06xyIv0xc7mJJHFfqEq-efWuRag9M3LW+9m7g5+6VT49jlHoESW6EWW7LEbcCaK1W+K3sJK6w6pzCekTFz1M7WpuMV5tgQCFBrFF7UhCUX21w8O9Es3t0ZtlAJtQZHjSLrawC0C3O4gNRNIJfX+lgQGgdPKHIYKKUrsAAGSUhiDlx-3r7osF3aFdOMdzxDQGNRsAjYA-jdAMer1iqWNfA5Zkyw72OMaY3OOdA9D9Afv6IHmkuD0a0qobxbyycT3BPg0SZAnVt3jleNvw3DYXEAQIkwvldUEIfQN5NJJIrSNfpGdIKpD7RRrUDWZYc-pWcyhaCuskBubf2wVT6pqweY89kBs0e7fgx9v6EYUH53Vowdv1uksDNOaRdUtZY0x3cE2CeJeZsWkpdK30XVxLgrhUcZd+FR6omA+Ad5cfDCuFcHNOIo1Q923nOHqXN2oo2e33PI+Y3-Y416gSGNGWVY-ER2tjcorS2-oZKbYiGhphByHCDMCudP2kcZ3QbNR-0HuaMoXAO6HxSs8l3hBl34unc5As2XfXvPVxWAZ3fpbiovvOHy3vupf6LSfic-eR7EN8Qyf8tBOCuyx7MivXhis0OTbx-ndQi69nMr0XM5aG+xw1Brj8Sf3pQTFPg17aajWlEO6N+J8cBdcRIPqfosT6UFJ28EDD4KifrMRO+2arX1Nn3bbMBrswuMh8TqBsoVJvCTg0gqE+eBv53Bvb4ims+3UXsmDMCkBnAwPcd3vsLQ6TMJevu6mS+4bS8CAWtHWgr1Wa1ZGKpDP0tswU4EACuURWvsVxoapljAz-M4BV2baHpqudLR8sgNQFjFu2yPEoiKRQEv9J+ONA6HdCbhJUUOM7R3lh1BZ-po0xAKNB1nE5qZow2QFgNRz87tMQ29eHmuG0MITkkszzMLoemiB10BeuWaxiNlKA9xW6A8THJ3THgmlxeNFYTgQA5bq1i+f3bcuX2gEhM-UGvcJjQzdr0NoeCTHjp3wtCW0lKGTFStq2BS+1kOi-S5AQn-KUQ+glRIAA

**Comment by giero** [comment] 2017-12-19 21:16
You don't have any water commander hero, but you have 3 (quite strong) Light commanders.

These 3 cards will make the most damage, but remember that commanders will give bonus to attack for all cards of the same affinity in deck. "Paladin Ivon" and "Tovar, the Wingless" have Light affinity (will gain that bonus from commanders) and they have the most attack after those 3 commanders.

Not a bug ;)

**Comment by shaunroot** [comment] 2017-12-19 21:21
Really? I had no idea! This is amazing information. I am so glad to have you and this app to help me out. So, every light commander gives a bonus to every light hero on the team? What is the multiplier that the non-commanders receive in this situation? Does this apply to slayers in slayer events as well?

I looked at it as, even if all light heroes got the bonus, it would be: Stellaris power 494 * 3(leader bonus) = 1482.
Javus power is 1076 * 3(commander)  = 3228.

Thank you so much!

**Comment by giero** [comment] 2017-12-19 21:37
Slayer event is the different type of event. You may want to read some tutorials from wiki:

http://legendarygame.wikia.com/wiki/Slayer
http://legendarygame.wikia.com/wiki/Commander

During Slayer event Slayer cards will gain multiplier only which is assigned to them.
During Commander event multipliers are accumulated between all cards of the same affinity.

If you have non-event card in deck:
during Slayer event: no multipliers for that card
during Commander event: will get multipliers  from all Commanders cards (of the same affinity) in deck

**Comment by shaunroot** [comment] 2017-12-19 21:45
I have read that, but I must be missing something. It appears to me that the light commanders boost the light non-commanders indirectly through the affinity gem multipliers. Players don't collect every bonus gem on every turn, so how do you calculate the value in that case?

This is all super interesting. Thanks!

**Comment by giero** [comment] 2017-12-19 21:58
Calculations are simplified to a variant, where you match only 3 gems of the same affinity. I know that during every round you have different combinations of gems, but if you assume you have only 3 gems of the same affinity, its' easier to compare different types of cards. Devs didn't publish the mechanics of this game anywhere, so I have to assume a lot of things ;) But it works so far :)

But the hardest to achieve will be to implement new game mechanics like "Intensity" - it's going to be more difficult to compose optimal decks, but we'll see :)

**Closed as completed** 2017-12-19 22:19 UTC
